### PR TITLE
Fix missing-braces issue for Rcomplex

### LINKED ISSUE #134: Flagging compiler issue
Hey Dirk! Wanted to flag that this form of declaration for `Rcomplex` is throwing compiler errors for us:

https://github.com/eddelbuettel/nanotime/blob/48d48a7b42e3bef173b5312b5fbb3c9b1776b40f/src/period.cpp#L188

Example:

```
nanotime/src/period.cpp:189:23: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
  189 |     res[i] = Rcomplex{pu.dbl2.d1, pu.dbl2.d2 };
      |                       ^~~~~~~~~~~~~~~~~~~~~~
      |                       {                     }
```

R 4.1.3, no issue, R 4.4.1, issue. I am pretty puzzled why we're seeing it but not you or CRAN.

We fixed it with `-DR_LEGACY_RCOMPLEX` per the <R_ext/Complex.h> header:

https://github.com/r-devel/r-svn/blob/fc865847f6f7110f06cb361027a7007f670c6733/src/include/R_ext/Complex.h#L33

Another fix is to do what the warning suggests and add an extra layer of `{}`, but that requires some `#if R_VERSION` mess I found more onerous.

This is very likely where the issue arose:

https://github.com/r-devel/r-svn/commit/862f9f816ff3ff3cb3f851603f19e99f60a98475

Which would have arrived in R 4.3.0:

https://github.com/wch/r-source/blob/tags/R-4-3-0/src/include/R_ext/Complex.h

Anyway, not sure if there's anything to do here (could be something idiosyncratic on our end), but sharing in case this does start showing up at some point. Feel free to close.

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #134. This approach avoids the need for old-vs-new preprocessor branching.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
No, not a fan of a preprocessor macro based approach, sorry.

File: src/period.cpp [hunk 1]
```diff
@@ -8,6 +8,14 @@
...
 #include "nanotime/utilities.hpp"
 
+// See comment in <R_Ext/Complex.h> in R>=4.3.0. As of 2024-10-30
+//   clang trunk with -Wmissing-braces requires the double-braced
+//   approach for creating Rcomplex objects.
+#if R_VERSION >= R_Version(4, 3, 0)
+#define RCOMPLEX(RE, IM) Rcomplex{{RE, IM}}
+#else
+#define RCOMPLEX(RE, IM) Rcomplex{RE, IM}
+#endif
```
Comment (eddelbuettel) [inline src/period.cpp:18]: That's not code I particularly like.

**Review by eddelbuettel — CHANGES_REQUESTED** [review]
Rejecting as using macros is step backwards.  An inline function with preprocessor step for clang > whateverthreshold may work.

**Comment by MichaelChirico** [comment]
Sure! Made it a routine instead, PTAL.

**Comment by MichaelChirico** [comment]
> preprocessor step for clang > whateverthreshold

I'm taking the approach of branching on R version because that's where the actual `typedef` for `Rcomplex` changes, a branch on the compiler would just be to avoid compiler warnings. If we think the warning is good+correct, the R version branching is better.

File: src/period.cpp (hunk 1 above)
Comment (eddelbuettel) [reply src/period.cpp:19]: I have almost the same code here now.  You are missing a leading `inline` (for slighly better performance / no function call overhead).

Comment (MichaelChirico) [reply src/period.cpp:19]: I see in your comment https://github.com/eddelbuettel/nanotime/issues/134#issuecomment-2448459585 you branched on `#ifdef R_LEGACY_RCOMPLEX`. Nice idea!

I think relying on that assumes R>=4.3.0, though, so I don't want to make it the primary branch. OTOH, _only_ branching on R version prevents any user that might need to use the legacy definition (for some reason?) from doing so. So I'll try and use both.

File: src/period.cpp [hunk 2]
```diff
@@ -8,6 +8,16 @@
 #include "nanotime/pseudovector.hpp"
 #include "nanotime/utilities.hpp"
 
+// See comment in <R_Ext/Complex.h> in R>=4.3.0. As of 2024-10-30
+//   clang trunk with -Wmissing-braces requires the double-braced
+//   approach for creating Rcomplex objects.
+inline Rcomplex makeComplex(double *re, double *im) {
+#if R_VERSION >= R_Version(4, 3, 0) && !defined(R_LEGACY_RCOMPLEX)
```
Comment (eddelbuettel) [inline src/period.cpp:15]: Double check is good.

File: ChangeLog [hunk 3]
```diff
@@ -1,3 +1,8 @@
+2024-10-30  Michael Chirico  <chiricom@google.com>
+
+    * src/period.cpp: Create `Rcomplex` objects in a more robust
+	  way that appeases `Wmissing-braces` compiler warnings on `clang`.
```
Comment (eddelbuettel) [inline ChangeLog:4]: One tab each please, in lines 3 and 4.

**Review by eddelbuettel — COMMENTED** [review]
Micro nags.  We're getting there.

**Review by eddelbuettel — APPROVED** [review]
Yup, that's pretty much what I would have done and the check on the R version may actually be net better than what I had in my first attempt.  We can live with this.

**Comment by MichaelChirico** [comment]
Argh. Sorry. I can't tell why. Do they give you and GHA artifacts that would include 00install.out? I didn't see any but I might just lack permissions.

Don't spend more than a few minutes on this, I'll try and figure out another way if it's causing you headache.

**Comment by eddelbuettel** [comment]
> Do they give you and GHA artifacts that would include 00install.out? 

We have to add a block such as towards the end of the file ci.yaml:

```
      - name: View Logs
        run: .run.sh dump_logs
        if: failure()
```

Otherwise I can try mac-builder later but I presume you have the requisite tar.gz handy?

File: src/period.cpp [hunk 4]
```diff
@@ -8,6 +8,15 @@
 #include "nanotime/pseudovector.hpp"
 #include "nanotime/utilities.hpp"
 
+// See comment in <R_Ext/Complex.h> in R>=4.3.0 and #134. Old
+//   approach to do `Rcomplex{ re, im }` now gives compiler issue
+//   on some compilers, R versions.
+inline Rcomplex makeComplex(double re, double im) {
```
Comment (MichaelChirico) [inline src/period.cpp:14]: I switched this to `(double re, double im)`. I _think_ that matches the previous behavior better, as `Rcomplex{re,im}` would create the `Rcomplex` object taking copies of `re`, `im`?

**Comment by MichaelChirico** [comment]
The earlier Mac issue was _probably_ due to my sloppy copy-pasting, I had

```c
makeComplex(double *re, double *im)
// then later
makeComplex(re, im); // Should be &re, &im!
```

Obviated the issue by just making copies (which I think we _need_ to do and IINM is what the original code was doing).

File: src/period.cpp [hunk 5]
```diff
@@ -8,15 +8,14 @@
 #include "nanotime/pseudovector.hpp"
 #include "nanotime/utilities.hpp"
 
-// See comment in <R_Ext/Complex.h> in R>=4.3.0. As of 2024-10-30
-//   clang trunk with -Wmissing-braces requires the double-braced
-//   approach for creating Rcomplex objects.
+// See comment in <R_Ext/Complex.h> in R>=4.3.0 and #134. Old
+//   approach to do `Rcomplex{ re, im }` now gives compiler issue
+//   on some compilers, R versions.
 inline Rcomplex makeComplex(double *re, double *im) {
```
Comment (eddelbuettel) [inline src/period.cpp]: Wait, I am just eye-balling this after dinner but this would required all calling instances to pass by (icky, to a C++ programmer) pointer.  Really?

File: src/period.cpp [hunk 6]
```diff
@@ -8,15 +8,14 @@
...
-#if R_VERSION >= R_Version(4, 3, 0) && !defined(R_LEGACY_RCOMPLEX)
-  return Rcomplex{{*re, *im}};
-#else
-  return Rcomplex{*re, *im};
-#endif
+  Rcomplex ret;
+  ret.r = *re;
+  ret.i = *im;
```
Comment (eddelbuettel) [inline src/period.cpp]: You can do the assignment by components when passing the standard way by & reference (possibly const &).

File: src/period.cpp (hunk 5 above)
Comment (MichaelChirico) [reply src/period.cpp]: NB this is stale

File: src/period.cpp (hunk 6 above)
Comment (MichaelChirico) [reply src/period.cpp]: resolving comment on earlier commit

File: src/period.cpp [hunk 7]
```diff
@@ -8,6 +8,15 @@
 #include "nanotime/pseudovector.hpp"
 #include "nanotime/utilities.hpp"
 
+// See comment in <R_Ext/Complex.h> in R>=4.3.0 and #134. Old
+//   approach to do `Rcomplex{ re, im }` now gives compiler issue
+//   on some compilers, R versions.
```
Comment (eddelbuettel) [inline src/period.cpp:13]: I would, if we could, like to edit the comment here somewhat at stress that 'modern' compilers and 'modern' C++ instantation get into each others ways on the _dual_ definition of the type, and that reverting to very plain C like assignment within the `struct` works.

Comment (MichaelChirico) [inline src/period.cpp:13]:
```suggestion
// From R>=4.3.0 the typedef of Rcomplex changed. Some modern strict
//   compilers (e.g. 2024 clang -Wmissing-braces) get tripped up by
//   'Rcomplex{re, im}' vs. 'Rcomplex{{re, im}}', the latter being technically
//   more correct for the new typedef, though for many compilers this will
//   "just work". See #134 and the comments in R_Ext/Complex.h.
```

Comment (MichaelChirico) [reply src/period.cpp:13]: OK, I proposed some phrasing as a suggested change. Let's edit that comment to satisfaction & then commit.
